name: Deploy to Server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        eval "$(ssh-agent -s)"
        ssh-add -L
        ssh-add -l
              
    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@${{ secrets.SERVER_HOST }} "cd /path/to/your/app && git pull origin dev && npm install && pm2 restart 0"
